name: "RL"
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - gymnasium
      - stable-baselines3
      - stable-baselines3[extra]
      - opencv-python
      - matplotlib
      - tensorboard
      - pandas
      - seaborn
      - tqdm
      - jupyterlab
      - ipykernel
      - ipywidgets
      - highway-env
      - pytest
      - torch
      - tensorboard
      - gymnasium[other]